apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: daniele-scaramuzzi-full-stack-node-app
  app.kubernetes.io/instance: daniele-scaramuzzi-full-stack-node-app-instance
  app.kubernetes.io/name: daniele-scaramuzzi-full-stack-node-app
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/danielescaramuzzi/full-stack-node-app
